before_script:
  - date
stages:
  - build
  - test
  - deploy
dev job:
  stage: deploy
  script:
    - echo "new_oa_map_dev"
    - git checkout dev-rem
    - git pull
    - npm install && CI=false npm run develop
    - npm prune --production
    - rsync -rvz --no-owner --no-group --no-perms --progress --exclude=".*" --delete $CI_PROJECT_DIR/ /data/new_oa_map
  only:
    - dev-rem
  tags:
    - "new_oa_map_dev"
master job:
  stage: deploy
  script:
    - echo "new_oa_map_master"
    - git checkout master
    - git pull
    - npm install && CI=false npm run build
    - npm prune --production
    - rsync -rvz --no-owner --no-group --no-perms --progress --exclude=".*" --delete $CI_PROJECT_DIR/ /data/map/new_oa_map
  only:
    - master
  tags:
    - "new_oa_map_master"
